cursor_trail 5
# url_color #0087bd
url_style curly
open_url_with default
detect_urls yes

enable_audio_bell no
# bell_path none
# active_tab_foreground   #000
# active_tab_background   #eee
active_tab_font_style   bold-italic
# inactive_tab_foreground #444
# inactive_tab_background #999
inactive_tab_font_style normal
# foreground #dddddd
# background #000000

background_opacity 0.9
background_blur 10

cursor_shape block
# cursor_text_color #111111




# BEGIN_KITTY_THEME
# Cyberpunk
include current-theme.conf
# END_KITTY_THEME

# BEGIN_KITTY_FONTS
font_family      family="SauceCodePro Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_fallback    Noto Color Emoji
# END_KITTY_FONTS
